/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/sites": {
    get: operations["GetSites"];
  };
  "/assets/{assetId}/properties": {
    get: operations["GetAssetProperties"];
  };
  "/user/get_users": {
    get: operations["GetUsers"];
  };
  "/user/invite_user": {
    post: operations["InviteUser"];
  };
  "/user/change_user_group": {
    post: operations["ChangeUserGroup"];
  };
  "/role/get_roles": {
    get: operations["GetRoles"];
  };
  "/group/get_groups": {
    get: operations["GetGroups"];
  };
  "/group/add_group": {
    post: operations["AddGroup"];
  };
  "/group/get_group_roles/{groupId}": {
    get: operations["GetGroupRoles"];
  };
  "/group/change_group_roles/{groupId}": {
    post: operations["ChangeGroupRoles"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    SiteGetAll: {
      data: ({
          country: {
            name: string;
          };
          postalCode: string | null;
          customerName: string | null;
          contactName: string | null;
          coordinates: {
            longitude: string;
            latitude: string;
          } | null;
          address: string | null;
          name: string;
          /** Format: double */
          id: number;
        })[];
    };
    AssetGetProperties: {
      assetProperties: ({
          property: {
            name: string;
            /** Format: double */
            id: number;
          };
          /** Format: double */
          value: number | null;
        })[];
      /** Format: double */
      relativeId: number | null;
      name: string | null;
    };
    TInviteUserBody: {
      group_id: string;
      email: string;
    };
    TChangeUserGroupBody: {
      userId: string;
      groupId: string;
    };
    TAddGroupBody: {
      mailNickname: string;
      name: string;
    };
    TChangeGroupRolesBody: {
      roleIds: string[];
    };
  };
  responses: {
  };
  parameters: {
  };
  requestBodies: {
  };
  headers: {
  };
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  GetSites: {
    responses: {
      /** @description Ok */
      200: {
        content: {
          "application/json": components["schemas"]["SiteGetAll"];
        };
      };
    };
  };
  GetAssetProperties: {
    parameters: {
      path: {
        assetId: number;
      };
    };
    responses: {
      /** @description Ok */
      200: {
        content: {
          "application/json": components["schemas"]["AssetGetProperties"];
        };
      };
    };
  };
  GetUsers: {
    responses: {
      /** @description Ok */
      200: {
        content: {
          "application/json": {
            data: ({
                group: {
                  name?: string;
                  id?: string;
                };
                /** @enum {number|null} */
                phone: null;
                email: string | null;
                lastName: string;
                firstName: string;
                id: string;
              })[];
          };
        };
      };
    };
  };
  InviteUser: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["TInviteUserBody"];
      };
    };
    responses: {
      /** @description Ok */
      200: {
        content: {
          "application/json": {
            success: boolean;
          };
        };
      };
    };
  };
  ChangeUserGroup: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["TChangeUserGroupBody"];
      };
    };
    responses: {
      /** @description Ok */
      200: {
        content: {
          "application/json": {
            success: boolean;
          };
        };
      };
    };
  };
  GetRoles: {
    responses: {
      /** @description Ok */
      200: {
        content: {
          "application/json": {
            data: {
                name: string;
                value: string;
                id: string;
              }[];
          };
        };
      };
    };
  };
  GetGroups: {
    responses: {
      /** @description Ok */
      200: {
        content: {
          "application/json": {
            data: {
                description: string;
                name: string;
                id: string;
              }[];
          };
        };
      };
    };
  };
  AddGroup: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["TAddGroupBody"];
      };
    };
    responses: {
      /** @description Ok */
      200: {
        content: {
          "application/json": {
            id: string;
          };
        };
      };
    };
  };
  GetGroupRoles: {
    parameters: {
      path: {
        groupId: string;
      };
    };
    responses: {
      /** @description Ok */
      200: {
        content: {
          "application/json": {
            data: {
                name: string;
                value: string;
                id: string;
              }[];
          };
        };
      };
    };
  };
  ChangeGroupRoles: {
    parameters: {
      path: {
        groupId: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TChangeGroupRolesBody"];
      };
    };
    responses: {
      /** @description Ok */
      200: {
        content: {
          "application/json": {
            success: boolean;
          };
        };
      };
    };
  };
}
